Improve --extend handling; --customize now required for customizations; logic simplification

diff --git a/sdm b/sdm
--- a/sdm
+++ b/sdm
@@ -316,7 +316,7 @@ EOF
 # Initialize and Parse the command
 #
 #
-version="V3.17"
+version="V3.18"
 sdmcommandline="$0 $@"      #Used in error messages
 apip="10.1.1.1"             #Default IP for the WiFi Captive Portal
 apssid="sdm"                #Default SSID for the WiFi Captive Portal
@@ -346,9 +346,9 @@ fcustomize=0                #True if customizing an image (either --customize or
 fbatch=0                    #1=nspawn "batch" mode (non-interactive). Do Phase1 and exit
 fdomount=0                  #1=Do a mount and drop into bash
 fexplore=0                  #1=Just fire up nspawn to explore the system
-fextendonly=0               #1=extend image by xmb MB and then exit
+fextend=0                   #1=extend image by --xmb MB
+fextendonly=0               #1=Just extend and exit (this if no other command specified)
 fnowpa=0                    #1=I really man no automatic no wpa config
-fphase1=0                   #Perform Phase 1 in the image
 fstab=""                    #Append this custom fstab to /etc/fstab
 hdmiforcehotplug=0          #1=Enable hdmi_force_hotplug in /boot/config.txt
 hdmigroup=""                #If set, edit /boot/config.txt and set
@@ -362,7 +362,6 @@ loadlocal=""                #Non-null specifies loading wifi creds on firstboot 
 locale=""                   #Locale
 myuser=""                   #Non-root user to create. Default is no non-root user created
 myuid=""                    #UID for non-root user if created
-noextend=0                  #1=Do not extend image
 noreboot=0                  #1=Do not restart system after first boot
 nspawnsw=""                 #Switches for nspawn
 poptions=""                 #Phase options
@@ -404,7 +403,7 @@ longopts="help,1piboot:,apps:,aptcache:,aptconfirm,aptmaint:,apip:,apssid:,\
 batch,bootadd:,bootconfig:,bootscripts,bootset:,burn:,burnfile:,\
 cscript:,csrc:,customize,datefmt:,ddsw:,dhcpcd:,dhcpcdwait,ecolors:,eeprom:,explore,exports:,extend,\
 fstab:,hdmi-force-hotplug,hdmigroup:,hdmimode:,host:,hostname:,info,keymap:,l10n,loadlocal:,locale:,\
-mcolors:,mount,noextend,norestart,noreboot,nspawnsw:,poptions:,reboot:,restart,\
+mcolors:,mount,norestart,noreboot,nspawnsw:,poptions:,reboot:,restart,\
 rootpwd,showapt,ssh:,svcdisable:,svcenable:,sysctl:,timezone:,uid:,user:,\
 wifi-country:,wificountry:,xapps:,xmb:,\
 custom1:,custom2:,custom3:,custom4:,version,nowpa,wpa:"
@@ -424,7 +423,7 @@ do
 	--aptcache)    aptcache=$2   ; shift 2 ;;
 	--aptconfirm)  aptconfirm=1  ; shift ;;
 	--aptmaint)    aptmaint="${2,,}"; shift 2 ;;
-	--batch)       fbatch=1      ; shift ;;
+	--batch)       fbatch=1      ; shift 1 ;;
 	--bootadd)     bootadd=$2    ; shift 2 ;;
 	--bootconfig)  bootconfig=$2 ; shift 2 ;;
 	--bootscripts) bootscripts=1 ; shift 1 ;;
@@ -442,9 +441,9 @@ do
 	--dhcpcdwait)  dhcpcdwait=1  ; shift 1 ;;
 	--ecolors)     ecolors=$2    ; shift 2 ;;
 	--eeprom)      eeprom=$2     ; shift 2 ;;
-	--explore)     fexplore=1    ; shift ;;
+	--explore)     fexplore=1    ; shift 1 ;;
 	--exports)     exports=$2    ; shift 2 ;;
-	--extend)      fextendonly=1 ; shift ;;
+	--extend)      fextend=1     ; shift 1 ;;
 	--fstab)       fstab=$2      ; shift 2 ;;
 	--hdmi-force-hotplug) hdmiforcehotplug=1 ; shift 1 ;;
 	--hdmigroup)   hdmigroup=$2  ; shift 2 ;;
@@ -456,18 +455,16 @@ do
 	--loadlocal)   loadlocal="${2,,}" ; shift 2 ;;
 	--locale)      locale=$2     ; shift 2 ;;
 	--mcolors)     mcolors=$2    ; shift 2 ;;
-	--mount)       fdomount=1    ; shift ;;
-	--noextend)    noextend=1    ; shift ;;
-	--norestart|--noreboot) noreboot=1 ; shift ;;
-	--nowpa)       fnowpa=1      ; shift ;;
+	--mount)       fdomount=1    ; shift 1 ;;
+	--norestart|--noreboot) noreboot=1 ; shift 1 ;;
+	--nowpa)       fnowpa=1      ; shift 1 ;;
 	--nspawnsw)    nspawnsw=$2   ; shift 2 ;;
-	--phase1)      fphase1=1     ; shift 1 ;;
 	--poptions)    poptions="${2,,}" ; shift 2 ;;
 	--reboot)      rebootwait=$2 ;
 		       reboot=1      ; shift 2 ;;
 	--restart)      reboot=1     ; shift 1 ;;
-	--rootpwd)     rootpwd=1     ; shift ;;
-	--showapt)     showapt=1     ; shift ;;
+	--rootpwd)     rootpwd=1     ; shift 1 ;;
+	--showapt)     showapt=1     ; shift 1 ;;
 	--ssh)         ssh=$2        ; shift 2 ;;
 	--svcdisable)  svcdisable=$2 ; shift 2 ;;
 	--svcenable)   svcenable=$2  ; shift 2 ;;
@@ -483,65 +480,67 @@ do
 	--custom2)     custom2=$2    ; shift 2 ;;
 	--custom3)     custom3=$2    ; shift 2 ;;
 	--custom4)     custom4=$2    ; shift 2 ;;
-	--version)     pvers=1       ; shift ;;
+	--version)     pvers=1       ; shift 1 ;;
 	--)            shift ; break ;;
 	-h|--help)     echo "sdm $version" ;
 echo "" ;
 echo "Usage:" ;
-echo "sudo /usr/local/sdm/sdm [switches] disk-image-file" ;
-echo "Customize a storage image (no --burn, --explore, or --extend)" ;
-echo "   sudo /usr/local/sdm/sdm sd-image-file" ;
-echo " or drop into an nspawn shell in the image (--explore)" ;
-echo "   sudo /usr/local/sdm/sdm --explore sd-image-file" ;
-echo " or burn an image to an storage device (--burn)" ;
-echo "   sudo /usr/local/sdm/sdm --burn /dev/sdx --host target-hostname sd-image-file" ;
-echo " or mount an image into file system for inspection/modification (Be VERY Careful!)" ;
-echo "   sudo /usr/local/sdm/sdm --mount sd-image-file" ;
+echo " sudo /usr/local/sdm/sdm --customize [switches] sd-image-file" ;
+echo "   Customize an SD Card image or SSD/SD Card" ;
+echo " sudo $0 --explore sd-image-file" ;
+echo "   Explore an SD Card image or SSD/SD Card" ;
+echo " sudo $0 --mount sd-image-file" ;
+echo "   Mount an SD Card image or SSD/SD Card" ;
+echo " sudo $0 --burn /dev/sdx --host target-hostname IMG-file" ;
+echo "   Burn the SD Card image to the burn device" ;
+echo " sudo $0 --aptmaint aptfunction sd-image-file" ;
+echo "   Do APT maintenance (update, upgrade) on an SD Card image or SSD/SD Card" ;
 echo "" ;
-echo "Switches" ;
-echo " --1piboot conf-file Use alternate 1piboot.conf" ;
-echo " --apip IPADDR       IP Address for WiFi Captive Portal [10.1.1.1]" ;
-echo " --apssid ssidname   SSID name for WiFi Captive Portal [sdm]" ;
+echo "Commands" ;
 echo " --burn devname      Copy the image to the storage device" ;
 echo " --burnfile filename Create a ready-to-burn customized Image file" ;
-echo " --host hostname     Hostname to burn into the image with --burn" ;
+echo " --customize         Customize the specified Image file" ;
 echo " --explore           Explore (nspawn shell) into image" ;
 echo " --info what         Display list of Locales, Keymaps, WiFi Countries, or Timezones" ;
 echo " --mount             Mount IMG file partitions and drop into bash" ;
-echo " --datefmt str       Date format for logs [%Y-%m-%d %H:%M:%S]" ;
-echo "  * Customization switches (no --burn, --explore, or --mount) *" ;
+echo "Command Switches for --customize and --burn or as noted";
+echo " --1piboot conf-file Use alternate 1piboot.conf" ;
 echo " --apps applist      List of app packages to install or @file with list" ;
 echo " --xapps applist     List of X11 packages to install or @file with list" ;
-echo " --aptcache serverip Use apt-cacher-ng with server 'serverip'" ;
+echo " --apip IPADDR       IP Address for WiFi Captive Portal [10.1.1.1]" ;
+echo " --apssid ssidname   SSID name for WiFi Captive Portal [sdm]" ;
+echo " --aptcache IPADDR   Use apt-cacher-ng with server 'IPADDR'" ;
 echo " --aptconfirm        Enable confirmation before apt commands" ;
 echo " --aptmaint options  Do apt commands batch-mode in the image (update, upgrade, autoremove)" ;
 echo " --batch             Perform customize operation and exit" ;
 echo " --bootadd key:value,key:value,... Add new keys and values to /boot/config.txt" ;
 echo " --bootconfig key:value,key:value,... Update and uncomment items in /boot/config.txt" ;
 echo " --bootset key:value,key:value,.. Set boot-time device settings (see README)" ;
+echo " --bootscripts       Run the scripts /usr/local/sdm/1piboot/0*-*.sh during first boot" ;
 echo " --cscript script    Custom Phase Configuration script" ;
 echo " --csrc dir          Source directory passed for Custom Phase scripts" ;
 echo " --custom[1-4] str   Can be used in Custom cscripts" ;
+echo " --datefmt str       Date format for logs [%Y-%m-%d %H:%M:%S]" ;
 echo " --ddsw str          Switches for dd command [bs=16M oflag=direct]" ;
 echo " --dhcpcd file       Append file to /etc/dhcpcd.conf" ;
+echo " --dhcpcdwait        Enable dhcpcd Wait for Internet" ;
 echo " --ecolors fg:bg:cur Set fg/bg/cursor colors when operating in the mounted IMG" ;
 echo " --eeprom str        Set the Pi eeprom directory" ;
 echo " --exports file      Copy named file to /etc/exports" ;
-echo " --extend            Only extend the image; no other customizations" ;
-echo " --noextend          Do not extend the image when doing customizations" ;
+echo " --extend            Extend the image by --xmb N MB [Default: 2048/2GB]" ;
 echo " --fstab file        Append file to /etc/fstab" ;
 echo " --hdmi-force-hotplug Set hdmi_force_hotplug=1 in /boot/config.txt" ;
 echo " --hdmigroup n       Set /boot/config.txt hdmigroup value" ;
 echo " --hdmimode n        Set /boot/config.txt hdmimode value" ;
 echo " --host hostname     Hostname to write onto the storage device with --burn" ;
-echo " --keymap keymapname Set keymap" ;
+echo " --keymap keymapname Set Keymap" ;
+echo " --L10n              Set Keymap, Locale, Timezone, and WiFi Country from running system" ;
 echo " --loadlocal args    Load WiFi Credentials from USB stick during first boot (see README)" ;
-echo " --locale localename Set the locale";
+echo " --locale localename Set the Locale";
 echo " --mcolors fg:bg:cur Set fg/bg/cursor colors when operating in --mount" ;
 echo " --nspawnsw str      Additional switches for nspawn command" ;
 echo " --poptions str      Set Phase 1 auto-run options" ;
 echo " --norestart         Do not restart after first boot" ;
-echo " --phase1            Run sdm Phase 1" ;
 echo " --reboot n          Restart the first boot of the system after n seconds" ;
 echo " --restart           Restart the first boot of the system" ;
 echo " --rootpwd           Set a root password into the image" ;
@@ -550,13 +549,13 @@ echo " --ssh none|socket   No ssh or ssh sockets [Default: ssh service]" ;
 echo " --svcdisable svc1,svc2,... Disable the named services" ;
 echo " --svcenable  svc1,svc2,... Enable  the named services" ;
 echo " --sysctl file       Copy the named file to /etc/sysctl.d" ;
-echo " --timezone tzname   Set the timezone" ;
+echo " --timezone tzname   Set the Timezone" ;
 echo " --uid uid           UID for non-root user [next free]" ;
 echo " --user username     Non-root user to create" ;
-echo " --wifi-country country Set WiFi country for unblocking WiFi" ;
+echo " --wifi-country country Set WiFi Country for unblocking WiFi" ;
 echo " --wpa wpaconf       wpa_supplicant.conf file to use" ;
 echo " --nowpa             Do not do WPA config file processing" ;
-echo " --xmb n             Extend image file by n MB [2048]" ;
+echo " --xmb n             Set the --extend size in MB [2048]" ;
 echo " --version           Print sdm version number" ;
 shift ; exit ;;
 	*) errexit "? $0: Internal error" ;;
@@ -572,7 +571,6 @@ source /usr/local/sdm/sdm-cparse           # Get function defs
 # Adjust settings based on switches and check for conflicting switches
 # and erroneous switch values
 #
-[ $fexplore -eq 1 ] && noextend=1
 
 if [ "$cscript" != "" ]
 then
@@ -627,11 +625,18 @@ cscript="$(fndotfullpath $cscript)"
 [ $fcustomize -eq 1 -a $fexplore -eq 1 ] && errexit "? Switch conflict: --customize and --explore"
 if [ "$aptmaint" != "" ]
 then
-    [ $(($burning+$fdomount+$fexplore+$fcustomize)) -gt 0 ] && errexit "? One or more switches conflict with --aptmaint"
+    [ $(($burning+$fcustomize+$fexplore+$fdomount)) -gt 0 ] && errexit "? One or more switches conflict with --aptmaint"
     aptfunction=1
 fi
-# Force customize if none of burn, mount, or explore
-[ $burning -ne 1 -a $fdomount -ne 1 -a $fexplore -ne 1 ] && fcustomize=1
+#
+# Ensure action requested: burn, mount, explore, aptmaint, customize
+#
+if [ $(($aptfunction+$burning+$fcustomize+$fexplore+$fdomount)) -eq 0 ]
+then
+    # Handle --extend only 
+    [ $fextend -eq 0 ] && errexit "? No command specified (--aptmaint --burn, --customize, --explore, --mount)"
+    fextendonly=1
+fi
 [ "$src" != "" -a ! -d "$src" ] && errexit "? Source directory '$src' not found"
 [ "$csrc" != "" -a ! -d "$csrc" ] && errexit "? Custom source directory '$csrc' not found"
 [ "$cscript" != "" -a ! -f "$cscript" ] && errexit "? Custom Phase Script '$cscript' not found"
@@ -664,24 +669,18 @@ exitiferr "$aptmaint"
 # Check sanity of the disk image argument
 #
 [ "$dimg" == "" ] && errexit "? No disk image specified"
+dimgdev=0
 if [ ! -f "$dimg" ]
 then
-    [ ! -b $burndev ] && errexit "? Disk image file '$dimg' does not exist"
-    [ $fdomount -eq 0 -a $fexplore -eq 0 ] && errexit "? Command cannot operate on device '$dimg'"
+    [ ! -b $burndev ] && errexit "? Disk image file or device '$dimg' does not exist"
     dimgdev=1
-else
-    dimgdev=0
 fi    
-
-if [ $aptfunction -eq 1 ]
-then
-    noextend=1
-    fextendonly=1
-    fnowpa=1
-fi
-
+#
+# Ensure wpa is correctly configured for the request, if needed
+#
 [ "$wpaconf" != "" -a ! -f "$wpaconf" ] && errexit "? wpa_supplicant config file '$wpaconf' not found"
 [ $fcustomize -eq 1 -a "$wpaconf" == "" -a $fnowpa -ne 1 ] && errexit "? Use --nowpa for no automatic wpa processing or --wpa to specify your wpa_supplicant.conf"
+
 if [ "$eeprom" != "" ]
 then
     if [[ ! "|critical|stable|beta|" =~ "|$eeprom|" ]]
@@ -689,6 +688,7 @@ then
 	echo "% --eeprom value '$eeprom' is not one of the standard 'critical/stable/beta'. Continuing..."
     fi
 fi    
+
 [ "$dhcpcd" != ""  -a ! -f "$dhcpcd" ]  && errexit "? --dhcpcd file '$dhcpcd' not found"
 [ "$exports" != "" -a ! -f "$exports" ] && errexit "? --exports file '$exports' not found"
 [ "$sysctl" != ""  -a ! -f "$sysctl" ]  && errexit "? --sysctl file '$sysctl' not found"
@@ -713,9 +713,12 @@ xappfile=$(findappfile "$xapps") #Ditto for xappfile and xapps
 exitiferr "$xappfile"
 xapps=$(getapplist "$xappfile")
 #
-# Process the command. Actions are burn, burnfile, mount, extend, explore, or customize
+# Process the command. Actions are burn, custommize, mount, and standalone --extend
 #
 thishost="$(hostname)"
+#
+# Process --burn command
+#
 if [ $burning -eq 1 ]
 then
     [ ! -d /mnt/sdm ] && mkdir /mnt/sdm
@@ -859,7 +862,9 @@ then
     [ $burn -eq 1 ] && echo "* Storage '$burndev' is ready" || echo "* Storage Image '$burnfilefile' is ready"
     exit 0
 fi
-
+#
+# Process --mount command
+#
 if [ $fdomount -eq 1 ]
 then
     domount
@@ -884,8 +889,10 @@ then
     resetcolors xt
     exit 0
 fi
-
-if [ $noextend -eq 0 ]
+#
+# Extend the image if --extend
+#
+if [ $fextend -eq 1 ]
 then
     echo "Extend disk image by ${imgext}MB..."
     extendimage "$dimg" "$imgext"
@@ -896,43 +903,56 @@ then
     echo " * (Ignore on-line resizing message) *"
     resize2fs ${loop}p2
 fi
-if [ $fextendonly -eq 0 -o $aptfunction -eq 1 ]
+if [ $fextendonly -eq 1 ]
 then
-    [ ! -d /mnt/sdm/boot ] && domount
-else
+    # --extend (only). Cleanup and exit
     docleanup
     exit 0
+else
+    # Not --extend (only)
+    [ ! -d /mnt/sdm/boot ] && domount
 fi
-
+#
+# Handle commands --aptmaint, --customize, and --explore
+#
 icolors=0    # Don't set colors around systemd-nspawn
-if [ -f $sdmdone -o $fexplore -eq 1 -o $aptfunction -eq 1 ]
+if [ $fcustomize -eq 0 ]
 then
-    if [ $aptfunction -eq 0 -a $fexplore -ne 1 ]
+    if [ "$aptmaint" != "" ]
     then
-	echo ""
-	echo "% It appears that '$dimg' is already customized"
-	echo "% Entering nspawn for you to have a look at it"
-	echo "  To re-enable this image for sdm in nspawn do: rm -f ${sdmdone#/mnt/sdm}"
-	echo "  Then exit nspawn and re-run this command: $sdmcommandline"
-	echo ""
+	fbatch=1
+	spawncmd="/usr/local/sdm/sdm-phase1 apt $aptmaint"
+	if [ ! -f /mnt/sdm/usr/local/sdm/sdm-phase1 ]
+	then
+	    echo "? sdm has not customized image '$dimg'"
+	    docleanup
+	    exit 1
+	fi
+    else
+	#
+	# Doing --explore
+	#
+	[ $dimgdev -eq 0 ] && echo "* nspawn into image '$dimg'" || echo "* nspawn into device '$dimg'"
 	spawncmd=""
 	icolors=1
-    else
-	if [ "$aptmaint" != "" ]
-	then
-	    fbatch=1
-	    spawncmd="/usr/local/sdm/sdm-phase1 apt $aptmaint"
-	else
-	    [ $dimgdev -eq 0 ] && echo "* nspawn into image '$dimg'" || echo "* nspawn into device '$dimg'"
-	    spawncmd=""
-	    icolors=1
-	fi
     fi
 else
     #
     # Doing a customization
     # Create and populate /usr/local/sdm and /etc/sdm in the IMG
     #
+    if [ -f $sdmdone ]
+    then
+	if ! askyn "** Image '$dimg' has already been customized. Redo?" "-n 1"
+	then
+	    echo ""
+	    echo "** You can explore the image with '$0 --explore $dimg'"
+	    docleanup
+	    exit 0
+	else
+	    echo ""
+	fi
+    fi
     pi1bootconf="$(fndotfullpath $pi1bootconf)"
     spawncmd="/usr/local/sdm/sdm-phase1"
     #
