Improve console screen boot handling for Desktop versions

diff --git a/sdm-cryptconfig b/sdm-cryptconfig
--- a/sdm-cryptconfig
+++ b/sdm-cryptconfig
@@ -199,7 +199,7 @@ EOF
     cat > /usr/local/bin/sdm-cryptfs-cleanup <<EOF
 #!/bin/bash
 
-function wait_startup_complete {
+function wait_startup_complete() {
     # $1 is the message to write
     local lc=0 msg=\$1
     while [[ "\$(systemctl show -p ActiveState graphical.target --value)" != "active" ]] && [[ "\$(systemctl show -p ActiveState multi-user.target --value)" != "active" ]]
@@ -214,32 +214,67 @@ function wait_startup_complete {
     done
 }
 
-echo  "sdm-cryptfs-cleanup: Starting; System will restart automatically when completed" > /dev/console
-[ -f /etc/sdm/sdm-readparams ] && source /etc/sdm/sdm-readparams
-[ -f /etc/sdm/assets/cryptbbh ] && cat /etc/sdm/assets/cryptbbh >| /etc/sdm/assets/gfxbbh && do_delayed_boot_behavior reboot
-echo  "sdm-cryptfs-cleanup: Clean up initramfs content" > /dev/console
-logger "sdm-cryptfs-cleanup: Clean up initramfs content"
+function echolog() {
+    local msg="\$1"
+    echo "\$msg" >/dev/console
+    logger "\$msg"
+}
+
+echolog "sdm-cryptfs-cleanup: Starting; System will restart automatically when completed"
+echolog "sdm-cryptfs-cleanup: Clean up initramfs content"
 mv /etc/initramfs-tools/hooks/luks-hooks /etc/initramfs-tools/hooks/.sdm.luks-hooks.old
 # Leave bash in initramfs rather than special case remove if no --sshbash PLUS required by sdmluksunlock
 grep -v -E "sdmcryptfs|mappername|sdmcrypto|sdmnopwd|/etc/sdm/assets/cryptroot" /etc/initramfs-tools/hooks/.sdm.luks-hooks.old > /etc/initramfs-tools/hooks/luks-hooks
 chmod 755 /etc/initramfs-tools/hooks/luks-hooks
 [ $xsshbash -eq 0 ] && [ -f /etc/dropbear/initramfs/dropbear.conf ] && sed -i "s/bash/cryptroot-unlock/" /etc/dropbear/initramfs/dropbear.conf
 rm -f /etc/sdm/assets/cryptroot/*.lek /etc/*.lek
-echo "sdm-cryptfs-cleanup: Rebuild initramfs" > /dev/console
-logger "sdm-cryptfs-cleanup: Rebuild initramfs"
+echolog "sdm-cryptfs-cleanup: Rebuild initramfs"
 update-initramfs -u
+
+if [ $xsdm -eq 1 ]
+then
+    [ -f /etc/sdm/sdm-readparams ] && source /etc/sdm/sdm-readparams || logger "% sdm-cryptfs-cleanup: Unable to find expected /etc/sdm/sdm-readparams"
+    [ -f /etc/sdm/assets/cryptbbh ] && cat /etc/sdm/assets/cryptbbh >| /etc/sdm/assets/gfxbbh && do_delayed_boot_behavior reboot | logger "% sdm-cryptfs-cleanup: /etc/sdm/assets/cryptbbh not found; Boot behavior setting may not be correct"
+else
+    if grep -q -s graphical /etc/sdmscdefault
+    then
+        echolog "sdm-cryptfs-cleanup: Reset systemctl default target to graphical.target"
+        systemctl set-default graphical.target
+# Don't enable these services since no 'splash' in cmdline.txt (see below)
+#        if grep -q -s splash /etc/sdmscdefault
+#        then
+#            for svc in plymouth-start plymouth-read-write plymouth-quit-wait # plymouth-reboot plymouth-quit
+#            do
+#                echolog "sdm-cryptfs-cleanup: Unmask service '\$svc'"
+#                systemctl unmask \$svc >/dev/null 2>&1
+#            done
+#        fi
+    fi
+    if [ $xquiet -eq 0 ]
+    then
+        if grep -q -s quiet  /etc/sdmscdefault
+        then
+            echolog "sdm-cryptfs-cleanup: Reset 'quiet' in cmdline.txt"
+            sed -i "s/rootwait/rootwait quiet/g"  /boot/firmware/cmdline.txt
+        fi
+# 'splash' in cmdline.txt  prevents booting after sdm-cryptfs-cleanup reboots (? because prompt to unlock disk is lost/hidden?)
+#        if grep -q -s splash /etc/sdmscdefault
+#        then
+#            echolog "sdm-cryptfs-cleanup: Reset 'splash' in cmdline.txt"
+#            sed -i "s/rootwait/rootwait splash/g" /boot/firmware/cmdline.txt
+#        fi
+    fi
+fi
 systemctl disable sdm-cryptfs-cleanup
 rm -f /etc/systemd/system/sdm-cryptfs-cleanup.service
 rm -f /etc/systemd/system/sdm-auto-encrypt.service
-[ -f /usr/bin/startlxde-pi ] && systemctl set-default graphical.target
 systemctl daemon-reload
+
 wait_startup_complete "sdm-cryptfs-cleanup: Wait for system startup to complete"
 secs=5
-logger "sdm-cryptfs-cleanup: The system will restart in \$secs seconds"
-echo "sdm-cryptfs-cleanup: The system will restart in \$secs seconds" > /dev/console
+echolog "sdm-cryptfs-cleanup: The system will restart in \$secs seconds"
 sleep \$secs
-logger "sdm-cryptfs-cleanup: System restarting now"
-echo "sdm-cryptfs-cleanup: System restarting now" > /dev/console
+echolog "sdm-cryptfs-cleanup: System restarting now"
 rm -f /usr/local/bin/sdm-cryptfs-cleanup
 sleep 2
 reboot
@@ -486,6 +521,7 @@ function doupdateconfig() {
 
     echo "> Updated cmdline:"
     cat /boot/firmware/cmdline.txt
+    echo ""
 
     echo "> Update /etc/fstab for the encrypted rootfs"
     sed -i "s#PARTUUID=[0-9a-zA-Z-]* */ #/dev/mapper/$xmapper / #" /etc/fstab
@@ -504,6 +540,9 @@ function doupdateconfig() {
 #
 # Main code
 #
+
+[[ ! $EUID -eq 0 ]] && errexit "? Please run as root: sudo $0 $*"
+
 xauthkeys=""
 xcrypto=""
 xdns=""
@@ -594,19 +633,22 @@ then
     systemctl disable sdm-auto-encrypt > /dev/null 2>&1
     rm -f /etc/systemd/system/sdm-auto-encrypt.service
 else
-    if [ -f /usr/bin/startlxde-pi ]
+    if [ "$(systemctl get-default)" == "graphical.target" ]
     then
 	#
 	# Desktop. Enable console boot and modify quietness unless --quiet
 	#
-	echo "> Enable console boot for next system restart; will be reset to graphical subsequently"
-	systemctl set-default multi-user.target
+	systemctl get-default >/etc/sdmscdefault
+	echo "> Enable console boot for next system restart; will be reset to $(systemctl get-default) subsequently"
+	systemctl -q set-default multi-user.target
 	if [ $xquiet -eq 0 ]
 	then
 	    echo "> Enable verbose system restart"
+	    grep -q -s quiet /boot/firmware/cmdline.txt && echo "quiet" >>/etc/sdmscdefault
+	    grep -q -s splash /boot/firmware/cmdline.txt && echo "splash" >>/etc/sdmscdefault
 	    sed -i "s/ quiet//g" /boot/firmware/cmdline.txt
 	    sed -i "s/ splash//g" /boot/firmware/cmdline.txt
-            for svc in plymouth-start plymouth-read-write plymouth-quit plymouth-quit-wait plymouth-reboot
+            for svc in plymouth-start plymouth-read-write plymouth-quit-wait # plymouth-reboot plymouth-quit
             do
                 systemctl mask $svc >/dev/null 2>&1
             done
