LUKS USB unlock key

diff --git a/plugins/cryptroot b/plugins/cryptroot
--- a/plugins/cryptroot
+++ b/plugins/cryptroot
@@ -18,7 +18,7 @@ phase=$1
 pfx="$(basename $0)"     #For messages
 args="$2"
 loadparams
-vldargs="|authkeys|crypto|dns|gateway|ihostname|ipaddr|netmask|mapper|ssh|uniquesshkey|noauto|"
+vldargs="|authkeys|crypto|dns|gateway|ihostname|ipaddr|keyfile|netmask|mapper|ssh|uniquesshkey|noauto|"
 rqdargs=""                   # |list|of|required|args|or|nullstring|
 assetdir="$SDMPT/etc/sdm/assets/$pfx"
 
@@ -41,10 +41,18 @@ then
 	    logtoboth "? Plugin $pfx: authkeys file '$authkeys' not found"
 	    exit 1
 	fi
+    else
+	[ "$ssh" != "" ] && { logtoboth "? Plugin $pfx: 'ssh' requires 'authkeys'" ; exit 1 ; }
+    fi
+    if [ "$keyfile" != "" ]
+    then
+	[ -f $keyfile ] || { logtoboth "? Plugin $pfx: keyfile '$keyfile' not found" ; exit 1 ; }
+	logtoboth "> Plugin $pfx: Save keyfile to /etc/sdm/assets/cryptroot (deleted later)"
+	cp $keyfile $assetdir
     fi
     if [ "$crypto" != "" ]
     then
-	[[ "aes|xchacha" =~ "$crypto" ]] || { logtoboth "? Plugin $pfx: Supported cryptos: aes and xchacha" ; exit 1 ; }
+	[[ "aes|xchacha" =~ "$crypto" ]] || [[ "$crypto" =~ "aes-" ]] || { logtoboth "? Plugin $pfx: Supported cryptos: aes and xchacha" ; exit 1 ; }
     fi
     logtoboth "* Plugin $pfx: Complete Phase 0"
 elif [ "$phase" == "1" ]
@@ -59,9 +67,12 @@ then
     [ -v ssh ] && ssh="y"
     cp -a $src/sdm-cryptconfig /usr/local/bin
     cp -a $src/sdmcryptfs /usr/local/bin
-    # $assetdir/mappername and $assetdir/sdmcrypto only for tracking, not used by sdm-cryptconfig
-    echo "cryptdevice=$mappername" > $assetdir/mappername
-    echo "cryptoname=$xcrypto" > $assetdir/sdmcrypto
+    # These are only for tracking, not used by sdm-cryptconfig
+    [ "$keyfile" != "" ] && keyfile="$(basename $keyfile)"
+    echo "$mappername" > $assetdir/mappername
+    echo "$xcrypto" > $assetdir/sdmcrypto
+    echo "$keyfile" > $assetdir/keyfile
+
     logtoboth "> Plugin $pfx: Install cryptsetup cryptsetup-initramfs cryptsetup-bin"
     doaptrpterror "install --no-install-recommends --yes cryptsetup cryptsetup-initramfs cryptsetup-bin"
     logtoboth "> Plugin $pfx: Enable sdm automatic disk encryption configuration with crypto '$xcrypto'"
@@ -72,6 +83,7 @@ then
     [ "$gateway" != "" ] && osw="${osw} --gateway $gateway"
     [ "$ihostname" != "" ] && osw="${osw} --hostname $ihostname"
     [ "$ipaddr" != "" ] && osw="${osw} --ipaddr $ipaddr"
+    [ "$keyfile" != "" ] && osw="${osw} --keyfile $keyfile"
     [ "$netmask" != "" ] && osw="${osw} --netmask $netmask"
     [ "$ssh" != "" ] && osw="${osw} --ssh"
     [ -v uniquesshkey ] && osw="${osw} --unique-ssh"
@@ -87,6 +99,7 @@ After=multi-user.target
 [Service]
 Type=simple
 ExecStart=/usr/local/bin/sdm-cryptconfig --sdm --reboot $osw
+#ExecStart=/usr/local/bin/sdm-cryptconfig --sdm $osw
 
 [Install]
 WantedBy=multi-user.target
@@ -158,10 +171,10 @@ then
 	plugin_addnote ""
 	plugin_addnote "    * On the way back up you'll once again be prompted for the rootfs passphrase (Without the 30 tries)"
 	plugin_addnote "    * The system will ask for the rootfs passphrase in this manner every time the system boots"
-	if [ -v ssh ]
+	if [[ -v ssh ]] || [[ -v keyfile ]]
 	then
 	    plugin_addnote ""
-	    plugin_addnote "    NOTE: You have configured SSH"
+	    plugin_addnote "    NOTE: You have configured SSH or a LUKS encryption keyfile"
 	    plugin_addnote "          Please review https://github.com/gitbls/sdm/blob/master/Docs/Disk-Encryption.md for important information"
 	fi
 	plugin_addnote ""
diff --git a/sdm-cparse b/sdm-cparse
--- a/sdm-cparse
+++ b/sdm-cparse
@@ -406,7 +406,12 @@ function ispdevp() {
 
 function getspname() {
     local dev="$1" pn="$2"
-    ispdevp $dev && echo "p${pn}" || echo "$pn"
+    ispdevp $dev && echo "${dev}p${pn}" || echo "${dev}${pn}"
+}
+
+function getpartname() {
+    local dev="$1" pn="$2"
+    ispdevp $dev && echo "p${pn}" || echo "${pn}"
 }
 
 function writeconfig() {
@@ -1020,7 +1025,7 @@ function sdm_spawn() {
     #    [[ -z "${SDMPT+z}" ]] test will work since it is defined
     #
     local nspawnsw="$1" nsp="$2" cmd="$3" spcmd="$4" args="" ta
-    local wtf wtfelf wtfarch rest sts hostarch hostpagesz
+    local wtf wtfelf wtfarch rest sts hostarch hostpagesz pcor
     if [[ "$virtmode" =~ "nspawn" ]]
     then
 	[ -t 0 ] && cmode="--console interactive" || cmode="--console pipe"
@@ -1052,12 +1057,23 @@ function sdm_spawn() {
 		logtoboth "?! systemd-nspawn failed on this IMG"
 		logtoboth "   Host system architecture: $hostarch with $hostpagesz byte pages"
 		logtoboth "   IMG binaries: $rest"
-		logtoboth "   Correct this error on this host by:"
-		logtoboth "    * sudoedit /boot/firmware/config.txt"
-		logtoboth "    * Add the following line:"
-		logtoboth "    * kernel=kernel8.img"
-		logtoboth "    * Reboot and rerun the sdm command"
-		logtoboth "   Details: https://github.com/raspberrypi/bookworm-feedback/issues/120"
+		pcor=1
+		if [ "$(type -p cryptsetup)" != "" ]
+		then
+		    rest="$(df /)"
+		    [[ "$rest" =~ "/dev/mapper" ]] && pcor=0
+		fi
+		if [ $pcor -eq 1 ]
+		then
+		    logtoboth "   Correct this error on this host by:"
+		    logtoboth "    * sudoedit /boot/firmware/config.txt"
+		    logtoboth "    * Add the following line:"
+		    logtoboth "    * kernel=kernel8.img"
+		    logtoboth "    * Reboot and rerun the sdm command"
+		    logtoboth "   Details: https://github.com/raspberrypi/bookworm-feedback/issues/120"
+		else
+		    logtoboth "?! The rootfs on this host is encrypted; this IMG cannot be processed on this host"
+		fi
 	    else
 		logtoboth "?! Unrecognized error from systemd-nspawn"
 		logtoboth "   Please open an issue at https://github.com/gitbls/sdm"
@@ -1313,8 +1329,8 @@ function updategptrootfs() {
     then
         declare -x SDMPT=$(makemtpt)
 	domount $dev "Device"
-        #gptuuid1=$(blkid ${burndev}$(getspname $burndev 1) | sed -n 's|^.*PARTUUID="\(\S\+\)".*|\1|p')
-	gptuuid2=$(blkid ${burndev}$(getspname $burndev 2) | sed -n 's|^.*PARTUUID="\(\S\+\)".*|\1|p')
+        #gptuuid1=$(blkid $(getspname $burndev 1) | sed -n 's|^.*PARTUUID="\(\S\+\)".*|\1|p')
+	gptuuid2=$(blkid $(getspname $burndev 2) | sed -n 's|^.*PARTUUID="\(\S\+\)".*|\1|p')
 	logtoboth "> Set GPT rootfs partition GUID in cmdline.txt"
 	sed -i "/^[[:space:]]*#/!s|^\(.*root=\)\S\+\(\s\+.*\)$|\1PARTUUID=${gptuuid2}\2|" $SDMPT/boot/firmware/cmdline.txt
 	logtoboth "> Set GPT partition GUIDs in fstab"
@@ -1365,7 +1381,7 @@ function expandpartition() {
     local dev=${fulldevname##/dev/}
     local part pname fsize partstart partend devsize partsize newend pbytes nbytes pend
 
-    pname=$(getspname $fulldevname 2)
+    pname=$(getpartname $fulldevname 2)
     part="${dev}${pname}"
     while read line
     do
@@ -1570,7 +1586,7 @@ function domount() {
     # Tree will be mounted on the mountpoint, which must be set with makemtpt or makemtptX
     #
     local dmimg=$1 imgtype=$2 mpoint=${3}
-    local p1="1" p2="2" pinfo csize bootstart bootsize rootstart rootsize mdir sts rootfsd lv=0
+    local p1="1" p2="2" pinfo csize bootstart bootsize rootstart rootsize mdir sts rootfsd lv=0 kf=""
 
     [ "$mpoint" == "" ] && mpoint=$SDMPT
     [ ! -d $mpoint ] && mkdir $mpoint
@@ -1623,8 +1639,8 @@ function domount() {
 	fi
 	notmounted $mdir && errexit "? Error mounting IMG '$dmimg'"
     else # imgtype=Device
-	p1=$(getspname $dmimg 1)
-	p2=$(getspname $dmimg 2)
+	p1=$(getpartname $dmimg 1)
+	p2=$(getpartname $dmimg 2)
 	[ "$(lvmfind $dmimg pv)" == "" ] && rootfsd=$dmimg || { rootfsd=$(lvmgetmapper $dmimg) ; lv=1 ; }
 	ismounted ${dmimg}${p1} && errexit "? Device $dmimg is already mounted"
 	if [ $lv -eq 1 ]
@@ -1640,7 +1656,8 @@ function domount() {
 	else
 	    if [ $fencrypted -eq 1 ]
 	    then
-		cryptsetup luksOpen ${dmimg}${p2} sdmcrypt
+		[ "$keyfile" != "" ] && kf="--key-file $keyfile"
+		cryptsetup luksOpen ${dmimg}${p2} sdmcrypt $kf
 		errifrc $? "? Cryptsetup failed to open ${dmimg}${p2}"
 		mount -v /dev/mapper/sdmcrypt $mpoint
 	    else
diff --git a/sdmcryptfs b/sdmcryptfs
--- a/sdmcryptfs
+++ b/sdmcryptfs
@@ -67,20 +67,16 @@ function getpartsize() {
 
 function checkdev() {
     local dev=$1
-    if [ -b $dev ]
-    then
-	return 0
-    else
-	echo "? Unrecognized device '$dev'"
-	return 1
-    fi
+    [[ -b $dev ]] && parted -ms $dev print >/dev/null 2>&1 && return 0
+    echo "? Unrecognized device or no disk in drive '$dev'"
+    return 1
 }
 
 function save_rootfs() {
     local dev=$1 sdisk=$2 partsize=$3
     local rootfs=$(getpartname $dev)
     checkdev $sdisk || return 1
-    pmsg "Save rootfs '$rootfs' to $sdisk"
+    pmsg "Save rootfs '$rootfs' to '$sdisk'"
     pbytes=$((partsize*4096))
     pgb=$(((pbytes / 1073741824)+1))
     pmsg "rootfs Save should take less than $pgb minutes"
@@ -88,24 +84,63 @@ function save_rootfs() {
     return 0
 }
 
+if [ ! -e /mnt ]; then
+    mkdir -p /mnt
+    sleep 1
+fi
+
+function config_keyfile() {
+    local kfl="" kfn
+
+    if [ -f /etc/sdmkeyfile ]
+    then
+	read kfn < /etc/sdmkeyfile
+	if [ "$kfn" != "" ]
+	then
+	    kfn=$(basename $kfn)
+	    if [ -f /etc/$kfn ]
+	    then
+		kfl="/etc/$kfn"
+	    else
+		echo "? Internal error: keyfile $kfn not found"
+	    fi
+	    if [ "$kfl" != "" ]
+	    then
+		pmsg "Add LUKS key '$kfn' from file $kfl"
+		pmsg "When prompted for an existing passphrase use the one you just created"
+		cryptsetup luksAddKey $rootfs $kfl
+		[ $? -ne 0 ] && echo "? cryptsetup returned an error adding key '$kfn': $?"
+		rm -f $kfl
+	    fi
+	fi
+    fi
+}
+
 function cryptpart() {
     local dev=$1
-    local rootfs=$(getpartname $dev)
-    local cipher="aes-cbc-essiv:sha256"
-    pmsg "Enable luks2 '$xcrypto' encryption on '$rootfs'"
-    pmsg "Enabling encryption could take up to a minute or two"
-    pmsg "OK to ignore superblock signature warning"
+    local cipher
     case "$xcrypto" in
 	xchacha)
 	    cipher="xchacha20,aes-adiantum-plain64"
-	;;
+	    ;;
+	aes)
+	    cipher="aes-xts-plain64"
+	    ;;
+	aes-*)
+	    cipher="$xcrypto"
+	    ;;
     esac
+
+    pmsg "Enable LUKS2 encryption on '$rootfs' with cipher '$cipher'"
+    pmsg "Enabling encryption could take a while"
+    pmsg "OK to ignore superblock signature warning"
 
     while [ 0 ]
     do
 	cryptsetup luksFormat --type luks2 --cipher $cipher --hash sha256 --iter-time 5000 --key-size 256 --pbkdf argon2i $rootfs
 	[ $? -eq 0 ] && break
     done
+    config_keyfile $dev
     return 0
 }
 
@@ -127,7 +162,7 @@ function restore_rootfs() {
     local rootfs=$(getpartname $dev)
     local cpartnum cpartstart cpartend cpartsize etc
     checkdev $sdisk || return 1
-    pmsg "Restore '$rootfs' from $sdisk"
+    pmsg "Restore '$rootfs' from '$sdisk'"
     pmsg "rootfs Restore should take about the same time as the rootfs Save"
     dd bs=4k count=$partsize if=$sdisk of=/dev/mapper/$cryptdevice
     pmsg "Restore complete; Expand rootfs..."
@@ -142,7 +177,7 @@ function restore_rootfs() {
         fi
     done < <(parted -ms /dev/mapper/$cryptdevice unit B print)
     pmsg "rootfs partition size: $cpartsize Bytes $(getgbstr $cpartsize)"
-    pmsg "cryuptsetup status for /dev/mapper/$cryptdevice:"
+    pmsg "cryptsetup status for /dev/mapper/$cryptdevice:"
     cryptsetup status /dev/mapper/$cryptdevice
     return 0
 }
@@ -152,7 +187,7 @@ function runall() {
     local rootfs=$(getpartname $dev)
     checkdev $dev || return 1
     checkdev $sdisk || return 1
-    pmsg "Shrink partition $rootfs and get its size"
+    pmsg "Shrink partition '$rootfs' and get its size"
     partsize=$(getpartsize $rootfs)
     pbytes=$((partsize*4096))
     pmsg "Device '$dev' rootfs size: $partsize 4K blocks $(getgbstr $pbytes)"
@@ -168,10 +203,10 @@ sdisk="$2"
 xcrypto=""
 [ -f /etc/sdmcrypto ] && read xcrypto < /etc/sdmcrypto
 [ "$xcrypto" == "" ] && xcrypto="aes"
-[[ "aes|xchacha" =~ "$xcrypto" ]] || errexit "? Supported cryptos: aes and xchacha"
+[[ "aes|xchacha" =~ "$xcrypto" ]] || [[ "$xcrypto" =~ "aes-" ]] || errexit "? Supported cryptos: 'aes' and 'xchacha'"
 cryptdevice="nomappername"
 datefmt="%Y-%m-%d %H:%M:%S"
-[ -f /etc/mappername ] && . /etc/mappername || echo "% Where is /etc/mappername?"
+[ -f /etc/mappername ] && read cryptdevice < /etc/mappername || echo "% Where is /etc/mappername?; Using cryptdevice 'nomappername'"
 runall $dev $sdisk 
 sleepsecs=10
 if [ "$SSH_CLIENT" == "" ]
