Exit on errors, write notes using plugin_addnote

diff --git a/plugins/samba b/plugins/samba
--- a/plugins/samba
+++ b/plugins/samba
@@ -20,6 +20,7 @@ pfx="$(basename $0)"     #For messages
 args="$2"
 vldargs="|workgroup|dhcp|do_debconf|shares|smbconf|"
 loadparams
+assetdir="$SDMPT/etc/sdm/assets/samba"
 
 if [ "$phase" == "0" ]
 then
@@ -28,18 +29,21 @@ then
     #
     logtoboth "* Plugin $pfx: Start Phase 0"
 
-    plugin_getargs $pfx "$args" "$vldargs"
+    plugin_getargs $pfx "$args" "$vldargs" || exit
     plugin_printkeys
+
+    mkdir -p $assetdir
 
     if [ "$smbconf" != "" ]
     then
 	if [ ! -f $smbconf ]
 	then
-	    logtoboth "% Plugin $pfx: Cannot find samba smbconf file '$smbconf'; ignoring"
+	    logtoboth "? Plugin $pfx: Cannot find samba smbconf file '$smbconf'"
+	    exit 1
 	else
-	    logtoboth "> Plugin $pfx: Copy samba smbconf '$smbconf' into IMG /etc/sdm/assets/samba-$(basename $smbconf)"
-	    rm -f $SDMPT/etc/sdm/assets/samba-$(basename $smbconf)
-	    cp -a $smbconf $SDMPT/etc/sdm/assets/samba-$(basename $smbconf)
+	    logtoboth "> Plugin $pfx: Copy samba smbconf '$smbconf' into IMG $assetdir/$(basename $smbconf)"
+	    rm -f $assetdir/$(basename $smbconf)
+	    cp -a $smbconf $assetdir/$(basename $smbconf)
 	fi
     fi
     if [ "$shares" != "" ]
@@ -48,9 +52,9 @@ then
 	then
 	    logtoboth "% Plugin $pfx: Cannot find samba shares file '$shares'; ignoring"
 	else
-	    logtoboth "> Plugin $pfx: Copy samba shares file '$shares' into IMG /etc/sdm/assets/samba-$(basename $shares)"
-	    rm -f $SDMPT/etc/sdm/assets/samba-$(basename $shares)
-	    cp -a $shares $SDMPT/etc/sdm/assets/samba-$(basename $shares)
+	    logtoboth "> Plugin $pfx: Copy samba shares file '$shares' into IMG $assetdir/$(basename $shares)"
+	    rm -f $assetdir/$(basename $shares)
+	    cp -a $shares $assetdir/$(basename $shares)
 	fi
     fi
     logtoboth "* Plugin $pfx: Complete Phase 0"
@@ -75,19 +79,19 @@ then
     doaptrpterror "install --no-install-recommends --yes samba" $showapt
     if [ "$smbconf" != "" ]
     then
-	if [ -f /etc/sdm/assets/samba-$(basename $smbconf) ]
+	if [ -f $assetdir/$(basename $smbconf) ]
 	then
-	    logtoboth "> Plugin $pfx: Replace /etc/samba/smb.conf with /etc/sdm/assets/samba-$(basename $smbconf)"
-	    mv /etc/samba/smb.conf /etc/samba/smb.conf.sdm-smbconf
-	    cp -a /etc/sdm/assets/samba-$(basename $smbconf) /etc/samba/smb.conf
+	    logtoboth "> Plugin $pfx: Replace /etc/samba/smb.conf with $assetdir/$(basename $smbconf)"
+	    mv /etc/samba/smb.conf /etc/samba/smb.conf.sdm
+	    cp -a $assetdir/$(basename $smbconf) /etc/samba/smb.conf
 	    setfileownmode /etc/samba/smb.conf 600
 	fi
     fi
     if [ "$shares" != "" ]
     then
-	if [ -f /etc/sdm/assets/samba-$(basename $shares) ]
+	if [ -f $assetdir/$(basename $shares) ]
 	then
-	    logtoboth "> Plugin $pfx: Append shares from /etc/sdm/assets/samba-$(basename $shares) to /etc/samba/smb.conf"
+	    logtoboth "> Plugin $pfx: Append shares from $assetdir/$(basename $shares) to /etc/samba/smb.conf"
 	    cp -a /etc/samba/smb.conf /etc/samba/smb.conf.sdm-shares
 	    setfileownmode /etc/samba/smb.conf.sdm-shares 600
 	    cat >> /etc/samba/smb.conf <<EOF 
@@ -95,7 +99,7 @@ then
 #** Following share definitions added by sdm samba plugin from $shares
 
 EOF
-     	    cat /etc/sdm/assets/samba-$(basename $shares) >> /etc/samba/smb.conf
+	    cat $assetdir/$(basename $shares) >> /etc/samba/smb.conf
 	fi
     fi
     #hostname sdm
@@ -114,18 +118,19 @@ else
     [ "$dhcp" == "" ] && dhcp="false"
     [ "$do_debconf" = "" ] && do_debconf="true"
 
-    logtoboth ""
-    logtoboth "> Plugin $pfx: *** samba service notes ***"
-    logtoboth "* Plugin $pfx:  Ensure that /etc/samba/smb.conf is as you want it"
-    logtoboth "* Plugin $pfx:  Add users and passwords using 'sudo smbpasswd'"
-    if [ "$smbconf" == "" -a "$shares" == "" ]
+    plugin_addnote ""
+    plugin_addnote "*** samba plugin service notes"
+    plugin_addnote ""
+    plugin_addnote " * Ensure that /etc/samba/smb.conf is as you want it"
+    plugin_addnote " * Add users and passwords using 'sudo smbpasswd'"
+    if [[ "$smbconf" == "" ]] && [[ "$shares" == "" ]]
     then
 	systemctl disable smbd > /dev/null 2>&1
-	logtoboth "* Plugin $pfx:  Use 'sudo systemctl enable --now smbd' to enable/start the service when complete"
+	plugin_addnote " * Use 'sudo systemctl enable --now smbd' to enable/start the service when configuration complete"
     else
-	logtoboth "* Plugin $pfx:  The service should be enabled when the system boots; review the system logs for possible errors"
+	plugin_addnote " * The smb service should be enabled when the system boots; review the system logs for possible errors"
     fi
-    logtoboth ""
+    plugin_addnote ""
     #logfreespace "at end of $pfx Custom Phase post-install"
     logtoboth "* Plugin $pfx: Complete Phase post-install"
 fi
