Improve FirstBoot messages

diff --git a/plugins/ufw b/plugins/ufw
--- a/plugins/ufw
+++ b/plugins/ufw
@@ -57,17 +57,17 @@ then
     logtoboth "> Plugin $pfx: Defer final ufw configuration/enable to First Boot"
     cat > $SDMPT/etc/sdm/0piboot/090-ufw.sh <<EOF
 #!/bin/bash
-logger "FirstBoot: Configure and Enable ufw"
+logger "sdm FirstBoot: Configure and Enable ufw"
 if compgen -G "/etc/sdm/assets/ufw/*" > /dev/null
 then
     for cufw in /etc/sdm/assets/ufw/*
     do
-        logger "FirstBoot: Run ufwscript \$cufw"
+        logger "sdm FirstBoot: Run ufwscript \$cufw"
         \$cufw
     done
 fi
 ufw enable
-[ \$? -ne 0 ] && logger "FirstBoot: ? ufw enable failed"
+[ \$? -ne 0 ] && logger "sdm FirstBoot: ? ufw enable failed"
 EOF
     logtoboth "* Plugin $pfx: Complete Phase post-install"
     #plugin_dbgprint "This is how to do a Plugin Debug printout"      # Will only be printed if --plugin-debug specified
